services:
  libation:
    image: ghcr.io/git-lemur/docker-libation-selkies:latest
    container_name: libation
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TITLE=Libation
      - CUSTOM_USER=admin
      - PASSWORD=password123 # RECOMMENDED: Change this password
    volumes:
      - ./config:/config
      - ./downloads:/config/Libation/Books
    ports:
      - 8080:8080
      - 8181:8181
    restart: unless-stopped
